apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    component: web # Important for recognition
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 30080
      protocol: TCP
